# Generated by Django 4.2.10 on 2024-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
